# **Upload quiz**: Putting the quiz to MongODB

_Reading in the data..._

In [2]:
# Importing pandas library
import pandas as pd

# Creating the dataframe
df = pd.read_json('questions.json')
df.head(3)

,text,options,correct,level
0,What is hate speech?,"[A. A funny joke, B. A compliment, C. Speech t...",A,e
1,Which of the following is an example of hate s...,"[A. Asking someone’s name, B. Insulting someon...",A,e
2,Hate speech often spreads through:,"[A. Newspapers, B. Face-to-face only, C. socia...",A,e

_Converting the correct answer..._

In [3]:
# Adding a new column
df['answer'] = df['correct'].apply(lambda x: 0 if x == 'A' else 1
                                   if x == 'B' else 2 if x == 'C' else 'D')

# Checking the answer
df['answer'].value_counts()

answer
0    57
2     1
1     1
Name: count, dtype: int64

_Updating the level of hardness..._

In [6]:
# Updating the level
df['level'] = df['level'].apply(lambda x : 0 if x == 'e' else 
                                1 if x == 'm' else 2)

# Checking the level
df['level'].value_counts()

level
1    20
2    20
0    19
Name: count, dtype: int64

_Addressing the answers_

In [11]:
# Identifying the answers
df['A'] = df['options'].apply(lambda x : list(x)[0].replace('A. ', ''))
df['B'] = df['options'].apply(lambda x : list(x)[1].replace('B. ', ''))
df['C'] = df['options'].apply(lambda x : list(x)[2].replace('C. ', ''))
df['D'] = df['options'].apply(lambda x : list(x)[3].replace('D. ', ''))
df.head(3)

,text,options,correct,level,answer,A,B,C,D
0,What is hate speech?,"[A. A funny joke, B. A compliment, C. Speech t...",A,0,0,A funny joke,A compliment,Speech that spreads hate or discrimination tow...,A news report
1,Which of the following is an example of hate s...,"[A. Asking someone’s name, B. Insulting someon...",A,0,0,Asking someone’s name,Insulting someone based on their religion,Wishing someone a good day,Telling a story
2,Hate speech often spreads through:,"[A. Newspapers, B. Face-to-face only, C. socia...",A,0,0,Newspapers,Face-to-face only,social media,Textbooks

_Resampling the dataframe..._

In [12]:
# Columns order
col_order = ['level', 'text', 'A', 'B', 'C', 'D', 'answer']

# Resampling the dataframe
df = df[col_order]

# Re-naming text
df.rename(columns = 
    {
        'text' : 'question'
    },
    inplace = True
)
# Checking dataframe
df.head(3)

,level,question,A,B,C,D,answer
0,0,What is hate speech?,A funny joke,A compliment,Speech that spreads hate or discrimination tow...,A news report,0
1,0,Which of the following is an example of hate s...,Asking someone’s name,Insulting someone based on their religion,Wishing someone a good day,Telling a story,0
2,0,Hate speech often spreads through:,Newspapers,Face-to-face only,social media,Textbooks,0

_Connection properties of database..._

In [13]:
# Importing custom pre-process text
import sys
import os
from dotenv import load_dotenv
from pathlib import Path

# Add the 'your_project' root directory to sys.path
# This assumes your_project is the parent of both 'data' and 'utils'
# os.path.abspath(__file__) would give you the notebook's path,
# then two '..' go up to 'your_project'
module_path = os.path.abspath(os.path.join('..', os.path.dirname('')))
if module_path not in sys.path:
    sys.path.append(module_path)

# Importing database connection
from utils.database import Database

# Ensrung we're at the root of the project
project_root = Path(os.getcwd()).resolve().parents[0]

# Constructin the path of the environment variable 
dotenv_path = project_root / 'credentials.env'

# Connecting to the correct environment path
load_dotenv(dotenv_path = dotenv_path)

# Retrieving properties of username
db_password = os.getenv('DB_PASSWORD')
db_string   = os.getenv('DB_STRING')

# Putting the password in the string
db_string = db_string.replace('<db_password>', db_password)

# Name of my database
db_name = 'Hate_App'
    
# Creating the database object
db = Database(connection_string = db_string, db_name = db_name)

# Name of collection to write
col_write = 'questions'

_Writing the data..._

In [15]:
# Putting questions in a list
questions = df.to_dict('records')

# Writing the questions
db.add_records(collection_name = col_write, records = questions)

[ObjectId('6865d532f9e8c0add70a8006'),
 ObjectId('6865d532f9e8c0add70a8007'),
 ObjectId('6865d532f9e8c0add70a8008'),
 ObjectId('6865d532f9e8c0add70a8009'),
 ObjectId('6865d532f9e8c0add70a800a'),
 ObjectId('6865d532f9e8c0add70a800b'),
 ObjectId('6865d532f9e8c0add70a800c'),
 ObjectId('6865d532f9e8c0add70a800d'),
 ObjectId('6865d532f9e8c0add70a800e'),
 ObjectId('6865d532f9e8c0add70a800f'),
 ObjectId('6865d532f9e8c0add70a8010'),
 ObjectId('6865d532f9e8c0add70a8011'),
 ObjectId('6865d532f9e8c0add70a8012'),
 ObjectId('6865d532f9e8c0add70a8013'),
 ObjectId('6865d532f9e8c0add70a8014'),
 ObjectId('6865d532f9e8c0add70a8015'),
 ObjectId('6865d532f9e8c0add70a8016'),
 ObjectId('6865d532f9e8c0add70a8017'),
 ObjectId('6865d532f9e8c0add70a8018'),
 ObjectId('6865d532f9e8c0add70a8019'),
 ObjectId('6865d532f9e8c0add70a801a'),
 ObjectId('6865d532f9e8c0add70a801b'),
 ObjectId('6865d532f9e8c0add70a801c'),
 ObjectId('6865d532f9e8c0add70a801d'),
 ObjectId('6865d532f9e8c0add70a801e'),
 ObjectId('6865d532f9e8c0add70a801f'),
 ObjectId('6865d532f9e8c0add70a8020'),
 ObjectId('6865d532f9e8c0add70a8021'),
 ObjectId('6865d532f9e8c0add70a8022'),
 ObjectId('6865d532f9e8c0add70a8023'),
 ObjectId('6865d532f9e8c0add70a8024'),
 ObjectId('6865d532f9e8c0add70a8025'),
 ObjectId('6865d532f9e8c0add70a8026'),
 ObjectId('6865d532f9e8c0add70a8027'),
 ObjectId('6865d532f9e8c0add70a8028'),
 ObjectId('6865d532f9e8c0add70a8029'),
 ObjectId('6865d532f9e8c0add70a802a'),
 ObjectId('6865d532f9e8c0add70a802b'),
 ObjectId('6865d532f9e8c0add70a802c'),
 ObjectId('6865d532f9e8c0add70a802d'),
 ObjectId('6865d532f9e8c0add70a802e'),
 ObjectId('6865d532f9e8c0add70a802f'),
 ObjectId('6865d532f9e8c0add70a8030'),
 ObjectId('6865d532f9e8c0add70a8031'),
 ObjectId('6865d532f9e8c0add70a8032'),
 ObjectId('6865d532f9e8c0add70a8033'),
 ObjectId('6865d532f9e8c0add70a8034'),
 ObjectId('6865d532f9e8c0add70a8035'),
 ObjectId('6865d532f9e8c0add70a8036'),
 ObjectId('6865d532f9e8c0add70a8037'),
 ObjectId('6865d532f9e8c0add70a8038'),
 ObjectId('6865d532f9e8c0add70a8039'),
 ObjectId('6865d532f9e8c0add70a803a'),
 ObjectId('6865d532f9e8c0add70a803b'),
 ObjectId('6865d532f9e8c0add70a803c'),
 ObjectId('6865d532f9e8c0add70a803d'),
 ObjectId('6865d532f9e8c0add70a803e'),
 ObjectId('6865d532f9e8c0add70a803f'),
 ObjectId('6865d532f9e8c0add70a8040')]