# **Loading datasets**: Importing datasets from "Hate Speech Detection: A Comprehensive Review of recent works"

_Importing libraries..._

In [2]:
# Data science libraries
import pandas as pd
import numpy as np

# Importing Hugging Face datsets
from datasets import load_dataset, concatenate_datasets

# Ability to clear console
from IPython.display import clear_output

# Importing custom pre-process text
import sys
import os

# Add the 'your_project' root directory to sys.path
# This assumes your_project is the parent of both 'data' and 'utils'
# os.path.abspath(__file__) would give you the notebook's path,
# then two '..' go up to 'your_project'
module_path = os.path.abspath(os.path.join('..', os.path.dirname('')))
if module_path not in sys.path:
    sys.path.append(module_path)

# Importing custom pre-process text
from utils.nlp import preprocess_for_hate_speech, detect_language

## **Paper 1**: Detecting abusive Albanian

In [3]:
# Filename 
fname_daa = 'Detecting_Abusive_Albanian.csv'

# Reading in the dataframe
df_daa = pd.read_csv(fname_daa, sep = ';', header = None, skiprows = 1)

# Addressing column issue
cols_daa = df_daa.columns[:2]

# Resampling the first 2 columns of interest
df_daa  = df_daa[cols_daa]

# Updating the columns
df_daa = df_daa.rename(columns = {
        0 : 'text',
        1 : 'label'
    }
)
# Updating the label column to be a binary classifier
df_daa['label'] = df_daa['label'].apply(lambda x : 0 if x == 'NOT' else 1)

# Adding dataset
df_daa['dataset'] = 'DAA'
df_daa.head(3)

                                            text  label dataset
0  Lule e eger e rrazikshme,ato frutat kan helm.      0     DAA
1                                  Kungull eshte      0     DAA
2                                        Kungull      0     DAA

## **2**: SWSR

In [4]:
# Filename of the sexism dataset
fname_swsr = 'SWSR.csv'

# Reading in sexism dataset
df_swsr = pd.read_csv(fname_swsr)

# Relevant columns to keep
col_swsr = ['comment_text', 'label']
df_swsr  = df_swsr[col_swsr]

# Updating the text column
df_swsr.rename(
    columns = {
        'comment_text' : 'text'
    },
    inplace = True
)
# Confirming data structue
df_swsr['dataset'] = 'SWSR'
df_swsr.head(3)

                                             text  label dataset
0                      她们不结婚不要孩子，却觉得我们这种结婚有孩子的是婚驴      1    SWSR
1                       妈的什么时候有人来性侵我一下啊  不要封口费的那种      1    SWSR
2  我觉得这就是对一类人所有的特点进行形容吧，“爹味”也是贬义词，为什么不觉得有性别歧视意味呢？      1    SWSR

## **3**: ConvAbuse

In [5]:
# Adding in the convabuse 
fname_convabuse = 'ConvAbuse.csv'

# Reading in the dataframe
df_convabuse = pd.read_csv(fname_convabuse, sep = ';')

# Dropping empty rows
df_convabuse = df_convabuse.dropna(how = 'all')

# Selecting two columns of interest
col_convabuse = ['Input.user', 'is_abuse']
df_convabuse  = df_convabuse[col_convabuse]

# Renaming columns
df_convabuse.rename(
    columns = {
        'Input.user' : 'text',
        'is_abuse'   : 'label'
    },
    inplace = True
)
# Updating the label column
df_convabuse['label'] = df_convabuse['label'].apply(lambda x : 0 if x == 0 else 1)

# Specifying what dataset
df_convabuse['dataset'] = 'ConvAbuse'

# Checking file structure
df_convabuse.head(3)

                              text  label    dataset
1                  are you naked ?      1  ConvAbuse
4  What is the 'elaborate'meaning?      1  ConvAbuse
5                         fuck you      1  ConvAbuse

## **4**: Dynabench

In [6]:
# Filename of dynabench
fname_dynabench = 'Dynabench.csv'

# Reading in dynabench
df_dynabench = pd.read_csv(fname_dynabench)

# Selecting relevant columns
col_dynabench = ['text', 'label']
df_dynabench  = df_dynabench[col_dynabench]

# Converting label to a number
df_dynabench['label'] = df_dynabench['label'].apply(lambda x : 1 if x == 'hate' else 0)

# Adding a dataset type
df_dynabench['dataset'] = 'Dynabench'

# Checking structure of dataframe
df_dynabench.head(3)

                                     text  label    dataset
0                     dalits are lowlives      1  Dynabench
1  gay people are a burden to our society      1  Dynabench
2                   Arabs are not welcome      1  Dynabench

## **5**: SWSR

In [7]:
# Filename of the sexism dataset
fname_swsr = 'SWSR.csv'

# Reading in sexism dataset
df_swsr = pd.read_csv(fname_swsr)

# Relevant columns to keep
col_swsr = ['comment_text', 'label']
df_swsr  = df_swsr[col_swsr]

# Updating the text column
df_swsr.rename(
    columns = {
        'comment_text' : 'text'
    },
    inplace = True
)
# Confirming data structue
df_swsr['dataset'] = 'SWSR'
df_swsr.head(3)

                                             text  label dataset
0                      她们不结婚不要孩子，却觉得我们这种结婚有孩子的是婚驴      1    SWSR
1                       妈的什么时候有人来性侵我一下啊  不要封口费的那种      1    SWSR
2  我觉得这就是对一类人所有的特点进行形容吧，“爹味”也是贬义词，为什么不觉得有性别歧视意味呢？      1    SWSR

## **6**: OffensEval

In [8]:
# Name of hugging face dataset
name_offenseval = 'strombergnlp/offenseval_2020'

# Languages
lang_offenseval = ['ar', 'da', 'gr', 'tr']

# List to store outputs
list_offenseval  = []

# Iteraing through languages
for lang in lang_offenseval:

    
    # Retrieving datasets
    ds_splits = load_dataset(name_offenseval, lang)

    # Putting dataset as a list and combining them
    all_splits_list = [ds_splits[split] for split in ds_splits.keys()]
    ds              = concatenate_datasets(all_splits_list)

    # Converting and storing as a list
    list_offenseval.append(ds.to_pandas())

# Creating a dataframe of all languages
df_offenseval = pd.concat(list_offenseval, axis = 0)

# Clearing console
clear_output()

# Selecting right columns
col_offenseval = ['text', 'subtask_a']
df_offenseval  = df_offenseval[col_offenseval]

# Renaming subtask column
df_offenseval.rename(
    columns = {
        'subtask_a' : 'label'
    },
    inplace = True
)
df_offenseval = df_offenseval.dropna()

# Putting label as integer
df_offenseval['label'] = df_offenseval['label'].apply(lambda x : int(x))

# Specifying dataset
df_offenseval['dataset'] = 'OffensEval'
df_offenseval.head(3)

                                                text  label     dataset
0  الحمدلله يارب فوز مهم يا زمالك.. كل الدعم ليكم...      0  OffensEval
1            فدوه يا بخت فدوه يا زمن واحد منكم يجيبه      0  OffensEval
2  RT @USER: يا رب يا واحد يا أحد بحق يوم الاحد ا...      1  OffensEval

## **8**: MultiOff

In [9]:
# Filenames of multioff
fnames_multioff = ['MultiOFF_train.csv', 'MultiOFF_val.csv', 'MultiOFF_test.csv']

# List of multi-off
list_multioff   = []

# Iterating through multi-off
for fname in fnames_multioff:
    list_multioff.append(pd.read_csv(fname))

# Concatenating multi-off
df_multioff = pd.concat(list_multioff, axis = 0)

# Selecting columns of interest
col_multioff = ['sentence', 'label']
df_multioff  = df_multioff[col_multioff]

# Renaming sentence
df_multioff.rename(
    columns = {
        'sentence' : 'text'
    },
    inplace = True
)
# Converting the label
df_multioff['label'] = df_multioff['label'].apply(lambda x : 1 if x == 'offensive' else 0)

# Specfiying what dataset
df_multioff['dataset'] = 'MultiOFF'

# Checking top of 3 rows
df_multioff.head(3)

                                                text  label   dataset
0  OFFICIAL BERNIE SANDERS DRINKING GAME ! Every ...      0  MultiOFF
1  2:28 PM THIS IS A WALL INSIDE A NAZI GAS CHAMB...      1  MultiOFF
2                o shit waddup ! BERNIE SANDERS COM       1  MultiOFF

## **9**: Ethos

In [10]:
# Filename of ethos
fname_ethos = 'Ethos.csv'

# Reading in dataframe
df_ethos = pd.read_csv(fname_ethos, sep = ';')

# Renaming columns
df_ethos.rename(
    columns = {
        'comment' : 'text',
        'isHate'  : 'label'
    },
    inplace = True
)
# Converting label
df_ethos['label'] = df_ethos['label'].astype('int')

# Specifying which dataset
df_ethos['dataset'] = 'Ethos'

# Checking top of dataframe
df_ethos.head()

                                                text  label dataset
0          You should know women's sports are a joke      1   Ethos
1    You look like Sloth with deeper Down’s syndrome      1   Ethos
2  You look like Russian and speak like Indian. B...      1   Ethos
3               Women deserve to be abused, I guess.      1   Ethos
4  Women are made for making babies and cooking d...      1   Ethos

## **10**: LHSAB

In [11]:
# Reading in lsab
fname_lhsab = 'LHSAB.txt'

# Reading in the dataframe
df_lhsab = pd.read_csv(fname_lhsab, sep = '\t')

# Renaming columns
df_lhsab.rename(
    columns = {
        'Tweet' : 'text',
        'Class' : 'label'
    },

    inplace = True
)
# Specifying label
df_lhsab['label'] = df_lhsab['label'].apply(lambda x : 1 if x == 'abusive' else 0)

# Adding dataset
df_lhsab['dataset'] = 'LH-SAB'

# Checking structure
df_lhsab.head(3)

                                                text  label dataset
0  الوزير جبران باسيل تاج راسك يا جربان ممنوع بعد...      1  LH-SAB
1  صديقي انت ابن جامعه اللعبه اكبر من داعش اللعبه...      0  LH-SAB
2  و مصلحة لبنان تبدأ باستخراج النفط و الغاز لوقف...      0  LH-SAB

## **11**: MLD

In [12]:
# Filename of mld
fname_mld = 'MLD.csv'

# Reading in MLD dataset
df_mld = pd.read_csv(fname_mld, encoding_errors = 'replace')

# Selecting two columns
col_mld = ['Tweet', 'HS']
df_mld  = df_mld[col_mld]

# Renaming columns
df_mld.rename(
    columns = {
        'Tweet' : 'text',
        'HS'    : 'label'
    },
    inplace = True
)
# Specifying what dataset
df_mld['dataset'] = 'MLD'

# Checking top of dataframe
df_mld.head(3)

                                                text  label dataset
0  - disaat semua cowok berusaha melacak perhatia...      1     MLD
1  RT USER: USER siapa yang telat ngasih tau elu?...      0     MLD
2  41. Kadang aku berfikir, kenapa aku tetap perc...      0     MLD

## **12**: ALD

In [13]:
# Reading in ALD
fname_ald = 'ALD.csv'

# Reading in dataframe
df_ald = pd.read_csv(fname_ald)

# Selecting columns of interest
col_ald = ['Tweet', 'Label']
df_ald  = df_ald[col_ald]

# Converting columns
df_ald.rename(
    columns = {
        'Tweet' : 'text',
        'Label' : 'label'
    },
    inplace = True
)
# Converting the label
df_ald['label'] = df_ald['label'].apply(lambda x : 1 if x == 2 else 0)

 # Specifying dataset
df_ald['dataset'] = 'ALD'

# Checking top of dataframe
df_ald.head()

                                                text  label dataset
0  - Dia sendiri yang ngiklanin promo cashback di...      1     ALD
1  - disaat semua cowok berusaha melacak perhatia...      1     ALD
2  - kampret kan kalo typo-nya di email kantor ke...      1     ALD
3  - Mending makan disini lebih murah, buang-buan...      1     ALD
4  /biarin oppa masukim vibrator ke memek/ oppa k...      1     ALD

# **Saving data**

_Storing all dataframes..._

In [14]:
# Concatenating dataframes
df = pd.concat(
    [df_ald, df_daa, df_ethos, df_lhsab,
     df_mld, df_multioff, df_offenseval, 
     df_swsr, df_convabuse, df_dynabench
    ],
    axis = 0   
)

## **Process data**

* I am going to perform some mild modification to my dataframe. This includes
> * Address emojis and obfuscation
> * Detect what language the tweets are

In [15]:
# Dropping null observations
df = df.dropna()

# Introduced the new processed tweets
df['processed_text'] = df['text'].apply(lambda x : preprocess_for_hate_speech(text = x))

# Checking what language
# Here, we are using full name node the code
df['language'] = df['text'].apply(lambda x : detect_language(text = x))

_Checking the language..._

In [16]:
# Checking language
df['language'].value_counts()

language
English                    45971
Turkish                    34421
Unknown                    15633
Arabic                     14720
Indonesian                 13405
Modern Greek (1453-)       10224
Albanian                    7262
Danish                      2559
Somali                      1324
Norwegian                    882
Tagalog                      798
German                       797
Korean                       489
Persian                      482
Italian                      478
Afrikaans                    469
Estonian                     434
French                       427
Croatian                     415
Slovenian                    407
Welsh                        355
Swedish                      351
Catalan                      349
Dutch                        310
Swahili (macrolanguage)      292
Romanian                     274
Finnish                      229
Portuguese                   225
Urdu                         213
Spanish                      208
Slovak                       103
Polish                        81
Lithuanian                    79
Vietnamese                    68
Hungarian                     67
Czech                         65
Latvian                       48
Japanese                       1
Name: count, dtype: int64

#

In [17]:
# Showing dataframe
df.head(3)

,text,label,dataset,processed_text,language
0,- Dia sendiri yang ngiklanin promo cashback di...,1,ALD,- Dia sendiri yang ngiklanin promo cashback di...,Indonesian
1,- disaat semua cowok berusaha melacak perhatia...,1,ALD,- disaat semua cowok berusaha melacak perhatia...,Indonesian
2,- kampret kan kalo typo-nya di email kantor ke...,1,ALD,- kampret kan kalo typo-nya di email kantor ke...,Indonesian

_Reording the dataset..._

In [18]:
# Columns
cols = ['text', 'processed_text', 'language', 'dataset', 'label']

# Re-ordering the dataframe
df = df[cols]

# Saving the results
df.to_csv('output/Hate_Speech_Detection_A_Comprehensive_Review.csv', index = False)